#! /bin/sh
rm -rf Makefile Makefile.in aclocal.m4 autom4te.cache/ config.guess config.h config.h.in config.log config.status config.sub configure depcomp doc/ install-sh libtool libunibreak.pc ltmain.sh missing stamp-h1 src/Makefile src/Makefile.in
